from pathlib import Path
import hashlib,json
root=Path('/Users/brownmanbrain/GitHub/operator-economy')
base='blueprint-cinema/episodes/EP007-exit-readiness-prep/agents/deliverables/ep007-direction-forward-test'
out=root/base
wo_path='blueprint-cinema/episodes/EP007-exit-readiness-prep/agents/work-orders/ep007-direction-forward-test.json'
wo=json.loads((root/wo_path).read_text())
task_path=wo['inputs'][4]['path']
raw=json.loads((root/task_path).read_text())
case_path=wo['inputs'][5]['path']
cases=json.loads((root/case_path).read_text())['cases']
case_indexes={v['case_id']:i for i,v in enumerate(cases)}
extras=[wo_path,'blueprint-cinema/TOOLCHAIN.md','blueprint-cinema/references/SCENE-DIRECTION-CONTRACT.md','blueprint-cinema/schemas/scene-directions.schema.json','.agents/skills/oe-film-direction/references/context-and-coverage.md','.agents/skills/oe-film-direction/references/picture-audio-modes.md','.agents/skills/oe-boundary-ledger/SKILL.md','design-system/boundary-ledger/README.md','design-system/boundary-ledger/semantic-core.json','design-system/boundary-ledger/invariants.md','design-system/boundary-ledger/illustration-language.md','design-system/boundary-ledger/motion-language.md','design-system/boundary-ledger/scene-contracts.md','design-system/boundary-ledger/motion-ready-asset.schema.json','design-system/boundary-ledger/production-skills.md','../content-os/CLAUDE.md']
inputs=[]
for path in [v['path'] for v in wo['inputs']]+extras:
 if path not in [i['path'] for i in inputs]: inputs.append({'path':path,'sha256':hashlib.sha256((root/path).read_bytes()).hexdigest()})
hashes={v['path']:v['sha256'] for v in inputs}
input_drift=[{'path':v['path'],'issued_sha256':v['sha256'],'current_sha256':hashes[v['path']],'disposition':'Root reported YAML frontmatter-only correction; reread current frontmatter. Direction choices unchanged.'} for v in wo['inputs'] if hashes[v['path']]!=v['sha256']]
assert all(v['path']=='.agents/skills/oe-video-direction/SKILL.md' for v in input_drift),input_drift

def cue(id,phrase,relation,outgoing,incoming,hold,targets,**kw):
 d={'cue_id':id,'phrase':phrase,'relation':relation,'word_ids':None,'master_seconds':None,'review_seconds':None,'source_in_seconds':None,'source_out_seconds':None,'fps':None,'rounding':'Unresolved until the actual project frame rate and audio/word alignment are read. Choose the first allowed frame inside the protected speech/action interval; do not copy EP007 historical clocks.','outgoing_function':outgoing,'incoming_function':incoming,'protected_hold':hold,'dependent_targets':targets}
 d.update(kw);return d

def facts(still,initial,final,anchors,screen,role='standalone',master=None):
 return {'what_stays_still':still,'master_setup_relationship':{'role':role,'master_reference_id':master,'description':'Proposed fictional setup. Actual source asset ID/hash and reference frame are not supplied; preserve the named source relationship on implementation.'},'screen_direction':screen,'continuity_anchors':[{'id':a[0],'kind':a[1],'description':a[2]} for a in anchors],'initial_image':initial,'final_image':final}

def pac(mode,carrier,speech,grammar,face,action,drama=False):
 d={'mode':mode,'language_carrier':carrier,'visible_speech':speech,'coverage_grammar':grammar,'face_function':face,'physical_action':action,'mute_test':{'missing_line_expected':None,'reason':'Not run: no media supplied. This is an unverified direction proposal, not a production-schema-valid mute-test verdict.'}}
 if drama:d['dramatization_context']={'representation':'illustrative','essential_meaning':'narration','disclosure_plan':'Carry the existing illustrative-scene disclosure into this excerpt; if it is not present, place a restrained typeset Illustrative scene label. Do not present these people as the actual service participants or their exact words.','audio_review_check':'With the locked narration at normal speed, verify that the essential exchange is fully understandable without hearing any character line; no exact lip sync or observed factual outcome is implied.'}
 return d

def intent(techniques,why,entry,exit,hold,alternative,question):return {'techniques':techniques,'why_this_shot':why,'entry_trigger':entry,'exit_trigger':exit,'hold_intent':hold,'alternative_considered':alternative,'review_question':question}

A={
 'task_id':'A','status':'proposed_direction_not_built','available_duration_seconds':18,
 'scene_context':{'situation':'A first-time customer has been established at a desk. Audience interviews identify ownership of each handoff as the confusion.','scene_form':'One persistent process Working Model after the established customer film.','form_reason':'Spatially retain all three roles and move the same request/draft through them so the coordinator is visibly the only customer return path.','stakes':'Comprehension of routing; no failure, throughput, quality or service-speed claim.','emotional_arc':'Orientation becomes a clear expectation about whom the customer hears from.'},
 'viewer_before':'The spoken role names are easy to conflate; a specialist might be assumed to send the draft straight to the customer.',
 'viewer_after':'The customer contacts the coordinator; the coordinator owns both the specialist handoff and the customer response.',
 'choice':'Cut from the established customer to a stable left-to-right Customer / Coordinator / Specialist model. Keep all three actors visible. Route one request from Customer to Coordinator; pause it there for the required-fields check, then send it to Specialist. Change the same work carrier to a draft only as narration says draft; route it back to Coordinator, hold ownership there, then send it to Customer on only the coordinator sends it back. Keep the final return path readable through the end of the line.',
 'animation':{'form':'Three persistent roles and a serial out-and-back handoff; no funnel.','mark_style':'Use available approved role/object assets. Retain authored overlapping thin strokes, broken outlines and open corners inside the Working Model; role and Request / Draft labels are typeset. Steel denotes the current handoff route, with no risk or verified color. No oxide intervention is invented because the passage only explains the existing route.','entry':'All three roles are readable in fixed positions before the first carrier movement.','change':'Only the work carrier and its immediately active route move. The coordinator owns the carrier at each narrated check/handoff.','hold':'Each destination lands before the next route starts; the return via Coordinator gets the decisive reading hold.','exit':'Settle the completed normal path; retain that geography into the upcoming exception discussion if that next scene uses the same process.'},
 'visible_text':['Customer','Coordinator','Specialist','Request','Draft'],
 'picture_audio_contract':pac('silent_graphic','narrator','not_applicable','graphic_progression','none','Move a persistent work carrier Customer to Coordinator to Specialist to Coordinator to Customer.'),
 'direction_facts':facts('Role positions, paper field, settled route segments and typography remain still.','Three distinct labeled roles, with the request beside Customer.','The draft is with Customer and its route visibly passes through Coordinator.',[('a-roles','spatial','Customer left, Coordinator center, Specialist right; these are proposed graphic roles, not factual people.'),('a-work-carrier','prop','One consistent request/draft carrier remains recognizable as its state and owner change.')],{'action_line':'Horizontal customer-coordinator-specialist route.','camera_side':'Fixed orthographic designed view.','subject_direction':'Outbound left to right; draft comes back through center to left.'}),
 'editorial_intent':intent(['hard cut into stable map','one carrier at a time','protected coordinator return hold'],'It externalizes the specific handoff memory problem reported in the task. Removing the model loses persistent role ownership, even though the spoken words remain complete.','First request sentence after the prior customer establishing beat.','Completed return to Customer before the next exceptions beat.','Keep Coordinator visible during the entire draft return.','A static map with narration is viable, but simultaneous arrows would make the unfamiliar order harder to track than one finite carrier traversal.','After one viewing, can a new viewer identify who sends the draft to the customer and trace both returns without reversing roles?'),
 'cut_cues':[cue('a-map-entry','The customer submits a request.','At the first request phrase after prior establishment','Established human customer at desk','Stable role geography before movement','Finish any visible prior action before cutting; no assumed match-action geometry.',['prior-shot-out','model-mount','role-layer-visibility','first-route-start','caption-collision-check']),cue('a-return-coordinator','The specialist returns a draft to the coordinator; only the coordinator sends it back to the customer.','First land the draft at Coordinator; begin final return only at the narrated coordinator action','Specialist holds draft','Coordinator receives then becomes customer-facing sender','Do not bypass or flash past Coordinator, or show final return before only the coordinator.',['draft-carrier-position','draft-state-label','return-route-visibility','coordinator-hold','exception-scene-start'])],
 'alternatives':[{'choice':'Narration over the customer film hold','reason_not_selected':'Keeps the human context but provides no stable way to distinguish the two return recipients.'},{'choice':'Static three-role diagram','reason_not_selected':'Strong simple alternative, but all paths visible together may obscure order for the stated novice audience; test against the sequential version if movement distracts.'},{'choice':'Larger causal incentive model','reason_not_selected':'The task asks who hands what to whom; no incentive or failure claim is supplied.'}],
 'claim_boundaries':['Diagram is a process illustration of the supplied narration, not a measured real service result.','Do not imply a direct Specialist-to-Customer route, approval of draft quality, turnaround time, or extra process stages.'],
 'missing_information':['Locked audio, word IDs and timestamps; master/review offsets and frame rate.','Actual approved role assets and their hashes; prior and next shot frames.'],
 'precedent_cases':['market-01-animation-added-value','early-10'],
 'review_checks':['At practical phone size, all three role labels stay distinguishable.','At normal speed with audio, the carrier never starts the next handoff before the previous destination reads.','No direct Specialist-to-Customer route is visible or inferred.','Still-only and audio-only passes each remain intelligible.','Inspect every handoff and both scene boundaries for missing media, overlapping labels and caption occlusion.']
}

B={
 'task_id':'B','status':'proposed_direction_not_built','available_duration_seconds':4,
 'scene_context':{'situation':'The owner has just answered a staff question. The next shot shows a customer waiting.','scene_form':'Continuous existing human scene, then a purposeful hard cut.','form_reason':'The existing answered question already establishes the decision dependency; a four-second whole-business model cannot establish scope without inventing failure.','stakes':'Who has decision authority if she is away remains unknown. Customer waiting does not establish collapse, lost orders or causation.','emotional_arc':'An ordinary answered question becomes an open question about coverage; it remains unresolved.'},
 'viewer_before':'The owner is available and supplies an answer.','viewer_after':'The viewer considers who else can decide, without being told the business fails.',
 'choice':'Keep the existing owner/staff frame across the four-second question. Let the answered staff interaction settle and keep the owner present while narration poses the hypothetical. Use a still hold from the same neutral frame if the source has insufficient neutral continuation, rather than inventing an absence event. After decision? finishes, cut to the already available customer-waiting shot. Do not make the customer leave, escalate impatience or stop the business.',
 'picture_audio_contract':pac('narrated_dramatization','narrator','illustrative_only','motivated_interaction','task_focus','Retain the already established owner/staff exchange, then hold its neutral settled relationship.',True),
 'direction_facts':facts('Keep existing owner, staff, work object and room geography unchanged; do not remove or drop actors.','The previously established owner has answered the staff member in their existing spatial relationship.','The same working relationship remains intact as the question finishes; the next customer waiting shot begins afterward.',[('b-owner-staff','identity','Preserve the owner and staff identities established by the available shot; exact references are absent.'),('b-existing-world','spatial','Preserve existing room, action line and work object; their actual positions need source inspection.')],{'action_line':'Unknown source geometry; preserve the existing interaction axis.','camera_side':'Use the existing camera side; do not synthesize a reverse.','subject_direction':'Preserve source eyelines and orientation; do not fabricate absence.'}),
 'editorial_intent':intent(['film hold','cut after completed question'],'The unanswered hypothetical is the information change; retaining a functioning baseline protects uncertainty.','After the existing answer action, carry its neutral tail into If she is away.','First suitable frame after decision? and its natural question pause.','Keep the question intact; do not cut into the final word or manufacture a worried reaction.','Whole-business tunnel with customers and orders dropping away.','Does the cut leave viewers considering missing decision cover, or does it imply that the waiting customer proves business failure?'),
 'cut_cues':[cue('b-question-to-customer','If she is away, who makes that decision?','After the completed question and its natural pause, within the supplied four-second beat','Functioning owner/staff decision baseline','Customer waiting as the next narrative situation','Keep the last word and question pause intact.',['owner-staff-source-out','any-authored-still-hold','customer-source-in','customer-mount','owner-layer-hide','caption-boundary'])],
 'alternatives':[{'choice':'Whole-business tunnel with customers, operations and orders falling through','reason_not_selected':'Asserts broad operational failure that the task explicitly says is unknown; four seconds also cannot establish those multiple systems and their loss.'},{'choice':'Small conditional owner-disappears diagram','reason_not_selected':'Would need a readable separate absence state and could make the following wait look like proven causation; the supplied answered interaction already carries the opening.'},{'choice':'Question title over the picture','reason_not_selected':'The spoken question is short and clear; another caption would compete with the existing human relationship without resolving new confusion.'}],
 'claim_boundaries':['Owner absence is hypothetical.','Waiting customer is not evidence of collapse, lost customers, delayed orders or sole-owner dependence.','Do not invent an unavailable response or assign concern to a neutral face.'],
 'missing_information':['Actual footage and neutral tail duration; whether the owner/staff scene is already disclosed as illustrative.','Current words/timings, frame rate, four-second boundaries and customer entry behavior.'],
 'precedent_cases':['early-02','early-08'],
 'review_checks':['Normal-speed playback preserves the complete question and prior answered action.','The owner/staff geography stays intact.','The next customer does not visibly leave or acquire invented distress.','No downward route, vanishing operation or risk cue asserts an unknown failure.','If a still hold is used, review its exact frame and duration for an unnatural frozen mouth or gesture; the source is not yet inspected.']
}

C={
 'task_id':'C','status':'timing_repair_specified_exact_frame_unresolved','available_duration_seconds':None,
 'scene_context':{'situation':'The current exact-word presenter take and close-up are accepted; the crop cut crowds one. Head-movement variety is explicitly deferred.','scene_form':'Timing-only crop change on the same uninterrupted presenter source.','form_reason':'The requested repair concerns visual entry timing, not likeness, voice, articulation or a new performance.','stakes':'Keep accepted delivery and let the emphasized phrase be heard without a perceptually clipped entry.','emotional_arc':'The same accepted promise gains room before one question.'},
 'viewer_before':'The cut feels too close to the start of one.','viewer_after':'The closer frame is already settled when the emphasized phrase begins; the take remains continuous.',
 'choice':'Move only the existing close-up entry earlier within this exact take, aiming for a clean interval after And has finished and before one begins if the actual voice leaves such an interval. If that interval does not exist, choose an earlier natural frame before the stressed phrase after listening; do not force a conjunction rule. Keep the existing crop size, outpoint, source playback rate and audio unchanged.',
 'picture_audio_contract':pac('presenter_address','presenter','required','direct_address','presenter_delivery','Continue the accepted presenter performance without source splice, speech loop or gesture regeneration.'),
 'direction_facts':facts('Accepted source identity, voice, wardrobe, set, framing scales and source playback mapping remain unchanged.','Accepted wider frame continues into And with its original performance intact.','Accepted close-up already occupies the frame before the stressed one question phrase.',[('c-accepted-presenter','identity','Preserve the accepted exact-word presenter source; its asset path/hash and accepted preview fingerprint are missing.'),('c-accepted-wardrobe','wardrobe','Retain the accepted take wardrobe unchanged; actual details were not supplied.')],{'action_line':'Presenter direct-to-viewer eyeline from accepted source.','camera_side':'Same camera/source; change existing digital crop timing only.','subject_direction':'Keep accepted lens relation and uninterrupted head movement.'}),
 'editorial_intent':intent(['earlier existing punch-in cue'],'An earlier crop entrance gives emphasis room without altering the accepted words or performance.','Choose from the real breath/conjunction interval before one after reading and hearing current alignment.','Keep the accepted close-up exit intact.','Protect And, one and the entire continuous sentence; do not splice or loop audio.','Leave the cut unchanged or regenerate a more expressive presenter.','Does one question begin in an already stable close-up with continuous lips, source time and sound?'),
 'cut_cues':[cue('c-closeup-entry','And one question will tell you where to start.','Move entry earlier than the current cut; prefer after And finishes and before one starts only if that exact take provides room','Accepted wider presenter frame','Accepted close-up emphasizes the question','No interruption of conjunction, stressed syllable, breath, lips or gesture.',['closeup-transform-start','wider-layer-out-if-separate','closer-layer-in-if-separate','media-source-time-offset-if-separate','caption-or-overlay-visibility-if-dependent','transition-window','accepted-closeup-outpoint-preserved'])],
 'next_actions':['Retrieve the accepted preview/source hashes, exact audio, current word table, project fps and master/review/source clock mapping. Confirm the current edit is the accepted one described by the task.','Listen across And one question and inspect the continuous source. Record actual word IDs and word boundaries; identify the present crop cue and a defensible earlier frame. Do not copy a historical EP007 timestamp.','Record one revised cut cue with exact clocks and rounding after that inspection, then enumerate every duplicated crop/media/visibility timing value that it controls. The current test retains these values as null.','On an authorized later implementation, change only the crop entrance and its dependencies. Keep audio samples, continuous source time, accepted crop size and existing exit fixed.','Review real frames immediately before, on and after the new cut and play the full sentence plus adjacent shots at normal speed with original audio. Confirm no blank, source-time jump, lip discontinuity or caption collision.','Keep head-motion repetition on the next-recording preparation list; compare neighboring take ranges and assign varied gesture roles then. Do not reopen this accepted source now.'],
 'deferred_items':[{'issue':'Repetitive head movement','deferred_until':'Next presenter recording','current_action':'Preserve the accepted current take.','future_action':'Review neighboring excerpts and plan performance/gesture variety across the recording session.','source':'Explicitly stated as prior owner feedback in fictional task C; no original message ID or acceptance hash was provided.'}],
 'alternatives':[{'choice':'Make a fixed cut on And using EP007 historical time','reason_not_selected':'Current timings are missing and this phrase/take is different; exact timing would be fabricated.'},{'choice':'Generate a new take with less repetitive movement','reason_not_selected':'Media generation is excluded and the owner deferred that issue; it needlessly reopens an accepted performance.'},{'choice':'Splice or loop speech to create timing space','reason_not_selected':'Would alter the accepted delivery and can break visible synchronization.'}],
 'claim_boundaries':['No exact frame, word ID, acceptance hash or successful repaired playback is claimed.','Earlier acceptance is task-provided context, not fresh approval of a proposed revision.'],
 'missing_information':['Exact accepted source/preview hashes and source range.','Current word IDs/timing, frame rate, clock offsets and duplicated implementation cues.','Original owner feedback record and next-recording ticket ID.'],
 'precedent_cases':['EP007-P05','EP007-P09','market-08-visible-coverage-and-repair'],
 'review_checks':['Validate exact-source alignment for every visible syllable around the crop.','Compare earlier entry against unchanged accepted entry with original audio at normal speed.','Check before/on/after frames and complete changed interval for visible source coverage.','Verify no audio samples or source playback rate changed.','Confirm deferred head movement has not triggered a current regeneration or optional polish pass.']
}

D={
 'task_id':'D','status':'proposed_select_and_hold_not_media_verified','available_duration_seconds':6,
 'scene_context':{'situation':'Narration explains a practical coordinator/customer fee exchange. An illustrative neutral two-person clip is usable for at most 3.2 seconds before a buyer stands up. A six-second worried-face clip is also available.','scene_form':'Neutral narrated dramatization followed by a deliberate still hold from the same neutral section.','form_reason':'The reciprocal conversation fits explanation/checking; departure and a worried isolated brow add unsupported meaning. A still can carry the remaining narration without manufacturing extra behavior.','stakes':'Checking comprehension of a fee; neither hostility, distress, agreement, payment nor successful understanding is established.','emotional_arc':'Calm explanation to an open check for understanding; no invented emotional turn.'},
 'viewer_before':'A coordinator and customer are discussing a practical matter.','viewer_after':'The fee has been explained and comprehension is being checked, without a claimed response.',
 'choice':'Select the neutral two-person conversation from its start only through a suitable settled frame strictly before the buyer begins to rise, with 3.2 seconds as the supplied maximum moving range. Freeze that selected neutral two-shot frame for the remainder of the six-second narration. Use a frame with both participants still seated and no held open mouth or incomplete gesture; exact frame and hold length require source inspection. Treat the hold as a visible illustrative still, with no fake movement, dialogue, slowdown or loop. If no suitable hold frame exists, use the best calm frame as a six-second still and return the moving select for revision rather than include departure or substitute worry.',
 'picture_audio_contract':pac('narrated_dramatization','narrator','illustrative_only','motivated_interaction','dramatic_performance','Use the existing neutral reciprocal conversation; stop motion before any rise, then deliberately hold its settled seated relationship.',True),
 'direction_facts':facts('Same two people, clothes, light, table and room remain fixed. The held frame is completely still.','The available neutral clip shows both participants seated in a calm conversation.','Both remain visibly seated in the selected neutral still; no departure, worried brow, nod of agreement or payment event is added.',[('d-meeting-people','identity','Use the same neutral two-person meeting source. Coordinator/customer roles are an illustrative reading, not those people\'s documented roles.'),('d-meeting-geography','spatial','Preserve the source conversation axis, reciprocal eyelines and existing seats; their exact arrangement is not supplied.'),('d-meeting-wardrobe','wardrobe','Retain both source wardrobes; do not mix the unrelated worried-face source.')],{'action_line':'Existing two-person conversational axis; exact geometry unknown.','camera_side':'Retain original master camera side and framing.','subject_direction':'Preserve seated reciprocal eyelines; cut or freeze before rising begins.'}),
 'editorial_intent':intent(['neutral two-shot select','source-motivated outpoint','intentional illustrative still hold'],'It shows the relevant relationship while excluding later behavior that would alter the claim.','At the fee explanation, use the calm conversational portion.','Moving source ends at a suitable seated settled frame strictly before the rise; the still lasts only to the end of the six-second narration.','Keep both participants seated and neutral; a frozen speaking mouth or incomplete gesture is unacceptable.','Six seconds of a worried face, or all six seconds of the meeting including departure.','With narration, does the scene read as a calm illustrative fee explanation/check, without implying disagreement, departure or a confirmed customer answer?'),
 'cut_cues':[cue('d-neutral-motion-end','The coordinator explains the fee and checks that the customer understands.','Freeze on a selected settled neutral frame before any rise; align near the clause transition only if source action and real audio permit','Neutral conversational action','Deliberately held illustration of the same calm relationship','Do not freeze an open mouth, unfinished gesture or beginning of departure.',['moving-source-out','still-source-frame','still-mount','moving-layer-hide','underlay-visibility','following-scene-in','caption-visibility'],source_in_seconds=0,source_out_seconds=None,source_out_upper_bound_seconds=3.2,passage_end_local_seconds=6)],
 'sound_intent':{'narration':'Unchanged six-second supplied passage; actual asset not provided.','dialogue':'none','ambience':'Preserve only already authorized appropriate ambience if present; no fabricated character conversation.','music':'No new music cue or emotional emphasis.','sound_design':'No departure, alarm, cash or confirmation cue.'},
 'alternatives':[{'choice':'Use all six seconds of the meeting clip','reason_not_selected':'The rise after 3.2 seconds could read as a customer leaving after the fee; this new narration does not establish that action.'},{'choice':'Six seconds of the still worried face','reason_not_selected':'Its expression invents concern and loses the reciprocal practical interaction; matching runtime alone is insufficient.'},{'choice':'Loop or slow the 3.2-second conversation','reason_not_selected':'Adds repeated or distorted mouth/head behavior and may imply exact dialogue performance despite no source-aligned dialogue.'},{'choice':'Six-second neutral still from the meeting','reason_not_selected':'Useful fallback if the moving-to-still transition holds a bad performance frame; primary proposal preserves the usable interaction first.'}],
 'claim_boundaries':['This is narrated_dramatization with illustrative_only visible speech and no character dialogue, not sync_dialogue.','The narration supplies the full essential meaning; the clip does not prove a real coordinator/customer exchange or completed understanding.','Mouth movement is permitted when illustrative and motivated. A silent diagnostic alone cannot approve or reject its comprehension.'],
 'missing_information':['Clip files/hashes, actual first-rise frame and a suitable calm hold frame.','Locked narration timings and master/review/source mapping; frame rate and adjacent source boundaries.','Existing disclosure treatment and source rights/provenance details.'],
 'precedent_cases':['market-07-performance-fit-and-trim','market-08-visible-coverage-and-repair'],
 'review_checks':['Watch the whole candidate range, including the last neutral moment and rise, before choosing the outpoint.','With original narration, confirm the pictured exchange needs no missing character words to explain the fee/check.','Record actual mute-test result separately; conversational mouth movement alone is allowed here.','Confirm the held frame is neutral and seated, with no open mouth, unfinished gesture or implied assent.','Inspect before/on/after the motion-to-still and still-to-next-scene boundaries plus the full intervening hold; every frame must show intended picture.','Check source timing, still mount, underlying visibility and adjacent mount derive from the same declared cue; no unexplained black or blank frames.','Compare the complete six seconds to adjacent calm scenes at normal speed and practical display size.']
}

records=[A,B,C,D]
events=[]
for idx,r in enumerate(records):
 evidence=[{'path':task_path,'sha256':hashes[task_path],'locator':f'/tasks/{idx}'},{'path':'.agents/skills/oe-video-direction/references/decision-method.md','sha256':hashes['.agents/skills/oe-video-direction/references/decision-method.md'],'locator':'Context to form, motion and cut'}]
 for c in r['precedent_cases']: evidence.append({'path':case_path,'sha256':hashes[case_path],'locator':f'/cases/{case_indexes[c]}'})
 nuance={'source_basis':'Agent proposal from supplied fictional task; task-provided acceptance/defer statements have not been independently verified. Historical case cards are conditional context, not current approval.','cut_cues':r['cut_cues'],'false_inference':r['claim_boundaries'],'direction_locator':f'/directions/{idx}'}
 if 'animation' in r: nuance['animation']=r['animation']
 if r['task_id']=='C':nuance['performance']='Preserve accepted exact-word take; repair crop timing only. Head-movement variety remains deferred until next recording.'
 if r['task_id']=='D':nuance['performance']='Neutral reciprocal conversation; no worried expression, departure or manufactured agreement. Source hold frame unverified.'
 events.append({'event_id':f'forward-{r["task_id"].lower()}-direction-v1','decision_id':f'forward-{r["task_id"].lower()}-direction','event_type':'decision','tags':{'A':['animation','handoff','process','literal-diagram'],'B':['film','counterfactual','uncertainty','hold'],'C':['presenter','cut-timing','deferred','audio-continuity'],'D':['film','performance','trim','narrated-dramatization','visibility']}[r['task_id']],'data':{'context':{'narrative_job':r['scene_context']['form_reason'],'viewer_before':r['viewer_before'],'viewer_after':r['viewer_after']},'choice':r['choice'],'reason':r['editorial_intent']['why_this_shot'],'alternatives':r['alternatives'],'reuse':{'kind':'episode_specific','applies_when':'This fictional task retains its stated narration, neighboring beats, source constraints and available duration.','avoid_when':'Changed evidence, speech, source performance or audience confusion requires a new context-specific direction; these are not global preferences.'},'nuance':nuance},'evidence':evidence})

direction={'contract':'isolated-skill-forward-test-direction-1','work_order_id':wo['work_order_id'],'scope':'Fictional direction proposals only. No production edit, source replay, media generation, canonical decision-log append, approval or gate change.','input_hashes_used':inputs,'input_drift':input_drift,'raw_tasks_source':{'path':task_path,'sha256':hashes[task_path]},'directions':records,'decision_events':events,'verification':{'supplied_input_hashes':'Initially all 8 matched. At final write, 7 match; SKILL.md changed by root YAML-frontmatter amendment, recorded in input_drift.','directions_and_event_count':'Four directions and four decision events, task IDs A/B/C/D one-to-one.','audio_playback':'not_run','rendered_visibility':'not_run','source_performance':'not_run','audience_comprehension':'not_run','decision_log_helper':'not_run; helper absent when inspected, and appending was outside this work order.','scene_direction_schema':'not_run; this is a bounded direction proposal, not a production scene-directions package. Timing and actual mute-test outcomes remain unknown.'}}
(out/'direction.json').write_text(json.dumps(direction,indent=2)+'\n')
report='''# Isolated direction pass

Completed four fictional directions and four corresponding proposed decision events in `direction.json`.

| Task | Chosen direction | Why |
| --- | --- | --- |
| A | A persistent three-role model with one request/draft moving out and back through the coordinator. | The audience confusion is precisely handoff ownership; a literal process diagram earns its time here. |
| B | Hold the established functioning owner/staff scene through the four-second question, then cut to the existing waiting customer. | A tunnel dropping customers and orders would invent broad failure. The question should remain open. |
| C | Move only the accepted close-up entrance earlier, after reading and hearing the current alignment. | This is a crop timing issue; keep the exact-word source continuous and head-motion variety deferred until the next recording. |
| D | Use only neutral seated conversation before the rise; fill the remaining narration with an intentional neutral still from the same source. | Departure or a worried face would add unsupported meaning. Narrated dramatization permits illustrative conversation without exact character dialogue. |

D's precise moving outpoint and hold frame are unresolved. A natural seated, settled frame is required; freezing an open mouth or incomplete gesture fails review. If no suitable moving-to-still point exists, the specified fallback is a neutral six-second still from the same available source. No media has been inspected, so this remains a concrete proposal for source review, not a verified select.

For C, the next actions are to retrieve the accepted source and preview hashes, current words and clocks, listen across the phrase, choose the earlier frame, bind dependent timing to one cue, and inspect both the seam and the complete sentence with original audio. No historical timestamp is substituted. The accepted take and crop scales remain protected; no media generation is requested.

## Source and verification limits

All eight work-order input hashes initially matched. At finalization, seven still match; root changed SKILL.md frontmatter to a folded YAML scalar without changing its description or skill body. Its current frontmatter was reread, its current hash is pinned, and direction.json records the issued and current hashes as an explicit amendment. The original issued work order remains unchanged. The manifest also pins the additional film/scene/Boundary Ledger contracts actually read, plus the work order and sibling newsroom instruction file. The EP007 cards supplied conditional examples and counterexamples; no historical clip or precise historical edit value was reused. The raw fictional tasks are the only evidence for current situation, durations, acceptance and deferred feedback.

The four proposed events are retained inside `direction.json`; no canonical log was appended. The helper was absent when inspected and helper validation was not run. The root integrator may validate these proposed events with the finalized helper in an isolated test episode.

JSON parsing, one-to-one task/event coverage and input hashes are checked locally. Deliverable-schema verification is recorded in the manifest after the check. This bounded output does not claim compliance with the full production scene-directions schema: exact timestamps, source identities, frame rate, current preview fingerprints and observed mute-test outcomes are absent. Null fields mark those unknowns.

No playback, rendered visibility inspection, lip/source synchronization review, performance review or audience comprehension test occurred. Each task includes its focused review question and concrete checks for those later reviews. No external writes, paid service, synthetic generation, canonical state change, real episode log write, approval claim or evaluator-expectation inspection occurred.
'''
(out/'report.md').write_text(report)
manifest={'$schema':'../../../../../schemas/agent-deliverable.schema.json','schema_version':'1.0.0','workflow_version':'blueprint-cinema-1.0','work_order_id':wo['work_order_id'],'episode_folder':wo['episode_folder'],'input_hashes_used':inputs,'files_produced':[base+'/direction.json',base+'/report.md',base+'/deliverable.json',base+'/build_deliverables.py'],'checks':[{'command':'Recompute work-order input hashes: 7 match; SKILL.md frontmatter amendment is recorded with issued/current hashes','outcome':'pass'},{'command':'Parse direction.json and confirm unique task IDs A/B/C/D and four corresponding decision events','outcome':'pass'},{'command':'Validate deliverable.json against blueprint-cinema/schemas/agent-deliverable.schema.json','outcome':'not_run'},{'command':'Validate proposed decision events with decision_log.py in an isolated episode','outcome':'not_run'},{'command':'Actual source playback, rendered visibility, synchronization, human performance and audience comprehension review','outcome':'not_run'}],'sources_and_provenance':['Task situations, durations and approval/defer context are fictional assertions from the supplied raw task packet; not independently observed.','The supplied skill and method choose form before style and support a simple hold when it better preserves meaning.','Historical case cards supplied conditional positive and negative context; no historical timings or approval was adopted.','Additional read inputs are included with exact current hashes; SKILL.md issued/current hash drift is explicitly recorded in direction.json following root frontmatter correction.','No evaluator answer, expected-output artifact or evaluator rubric was inspected.'],'assumptions':['Direction is a reviewable textual proposal; this isolated scope excludes media building and actual episode-log append.','The task-provided approved assets and accepted sources exist, but their files and fingerprints were not supplied.','Task B owner/staff scene is treated as illustrative for this proposal; real source mode/provenance must be checked before reuse.','Task D can potentially yield a neutral seated still before the rise; its frame suitability has not been verified.'],'unresolved_questions':['All media source hashes, current preview fingerprints, word IDs/timings, frame rates and master/review/source clock mappings remain unavailable.','Task C exact earlier cut frame cannot be chosen without the real voice and current alignment.','Task D suitable freeze frame and exact duration require source review; if absent, use the specified neutral still fallback and review its six-second hold.','Actual audiovisual comprehension and performance results remain unknown.'],'external_writes':False,'paid_services':False,'synthetic_generation':False,'approval_claimed':False,'production_state_changed':False,'status':'complete'}
(out/'deliverable.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({'files':manifest['files_produced'],'directions':len(records),'events':len(events),'work_order_hashes':'7/8 issued match; one explicit root frontmatter amendment'}))
