from pathlib import Path
import hashlib,json,wave,datetime
ROOT=Path('/Users/brownmanbrain/GitHub/operator-economy')
OUT=Path(__file__).resolve().parent
WO=ROOT/'blueprint-cinema/episodes/EP007-exit-readiness-prep/agents/work-orders/r39-callback-production.json'
work=json.loads(WO.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):(OUT/n).write_text(json.dumps(x,indent=2)+'\n')
with wave.open(str(OUT/'context-original-c.wav'),'rb') as w:raw=w.readframes(w.getnframes())
with wave.open(str(OUT/'callback-only.wav'),'rb') as w:
    assert w.getnframes()==86000 and w.readframes(w.getnframes())==raw[:172000]
recognized=''.join(x['text'] for x in json.loads((OUT/'callback-transcript.json').read_text())['transcription']).lower().strip()
assert recognized=='back to his question then.',recognized
model=OUT/'ggml-tiny.en.bin'
save('LOCAL-ASR-PROVENANCE.json',{'purpose':'Independent offline wording and boundary check; no paid transcription call.','tool':'whisper-cli installed at/opt/homebrew/bin/whisper-cli','model_source':'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin','model_path':str(model.relative_to(ROOT)),'model_sha256':sha(model),'model_bytes':model.stat().st_size,'source_audio':'context-original-c.wav','asr_derivative':'context-asr-16k.wav','derivation':'ffmpeg resampling to16000Hz for ASR only; native audio preserved.','recognized_callback':recognized,'timestamp_limit':'Model word timestamps are approximate; PCM silence inspection supplies final cutpoint.'})
save('CALLBACK-CUT.json',{'source':{'path':str((OUT/'context-original-c.wav').relative_to(ROOT)),'sha256':sha(OUT/'context-original-c.wav')},'native_samples_half_open':[0,86000],'native_seconds':[0,86000/48000],'duration_frames24':43,'output_pcm_unchanged':{'path':str((OUT/'callback-only.wav').relative_to(ROOT)),'sha256':sha(OUT/'callback-only.wav')},'level_derivative':{'path':str((OUT/'callback-level-matched.wav').relative_to(ROOT)),'sha256':sha(OUT/'callback-level-matched.wav'),'gain_db':-2.56,'retime':False,'fades':False},'replaces_original_master_interval':[250.625,252.41666666666666],'review_interval':[247.625,249.41666666666666],'no_timeline_shift_needed':True,'original_question_audio_preserved_from_master':252.41666666666666,'low_energy_interval_at_minus48db':[1.580292,2.222792],'source_word_check':recognized,'native_speed_listening':'Not performed by this worker; root must review timbre, level and sentence entrance.'})
base_path=ROOT/'blueprint-cinema/schemas/agent-deliverable.schema.json'
base=json.loads(base_path.read_text());local=json.loads(base_path.read_text())
local['$id']='urn:oe:r39-authorized-media-deliverable'
for k in ['external_writes','paid_services','synthetic_generation']:local['properties'][k]={'const':True}
save('authorized-media-deliverable.schema.json',local)
save('SCHEMA-EXCEPTION.json',{'base_schema':str(base_path.relative_to(ROOT)),'base_sha256':sha(base_path),'issued_work_order':str(WO.relative_to(ROOT)),'work_order_sha256':sha(WO),'conflict':'Base schema forces external_writes/paid_services/synthetic_generation false while issued work order explicitly authorizes true.','resolution':'Truthful true values plus local schema copy with only three constants adjusted. No shared contract was changed.','base_schema_validation':'Expected three constant failures; all other fields conform.','local_schema_validation':'Validated by finalize invocation.'})
inputs=work['inputs']+[{'path':str(WO.relative_to(ROOT)),'sha256':sha(WO)}]
files=[str(p.relative_to(ROOT)) for p in OUT.iterdir() if p.is_file() and p.name!='deliverable.json']
save('deliverable.json',{'$schema':'./authorized-media-deliverable.schema.json','schema_version':'1.0.0','workflow_version':'blueprint-cinema-1.0','work_order_id':'r39-callback-production','episode_folder':'EP007-exit-readiness-prep','input_hashes_used':inputs,'files_produced':files,'checks':[{'command':'Verify every issued input pin and current authorization caps','outcome':'pass'},{'command':'Exactly one Google guide and one ElevenLabs transfer; no paid retries','outcome':'pass'},{'command':'Live account/voice preflight and actual duration before transfer; conservative estimate168credits <=250','outcome':'pass'},{'command':'HTTP200 receipts; ElevenLabs character-cost122 <=250; Google conservative computed cost0.0060845 <=0.05','outcome':'pass'},{'command':'Exact PCM callback extraction and independent local ASR wording check','outcome':'pass'},{'command':'Native-speed listening against original adjacent narration','outcome':'not_run'},{'command':'Base standard schema boolean constants for authorized production','outcome':'fail'},{'command':'Local authorization-compatible schema and all remaining base-schema fields','outcome':'pass'}],'sources_and_provenance':['Authorized exact request packet and Original C transfer settings.','Live Google and ElevenLabs provider receipts; credentials never logged.','Official ElevenLabs documentation for shared voice multipliers.','Open Whisper tiny.en model downloaded for local transcription; no external audio upload beyond authorized Google/ElevenLabs production.'],'assumptions':['Response character-cost is stronger request-specific billing evidence than immediate account usage delta.','Gated RMS level matching is a starting point for seam listening, not perceptual certification.'],'unresolved_questions':['Root must listen to the level-matched callback in surrounding original narration before final selection.','Google cost is computed from rates; no invoice was returned.','Shared agent schema does not support paid worker actions despite issued authorization; local exception is recorded.'],'external_writes':True,'paid_services':True,'synthetic_generation':True,'approval_claimed':False,'production_state_changed':False,'status':'complete'})
print('R39 production packet complete.')
