import React from 'react';
import {AbsoluteFill,Audio,Easing,Img,OffthreadVideo,Sequence,interpolate,spring,staticFile,useCurrentFrame} from 'remotion';
import {COLORS,FONTS} from './theme';

const FPS=30;
const s=(n:number)=>Math.round(n*FPS);
const media=(n:string)=>staticFile(`coverage/direct-booking-recovery/${n}`);
const ease=Easing.bezier(.4,0,.2,1);
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const grid={backgroundImage:'linear-gradient(rgba(245,240,230,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(245,240,230,.055) 1px,transparent 1px)',backgroundSize:'64px 64px'};

const Source:React.FC<{children:React.ReactNode,dark?:boolean}>=({children,dark})=><div style={{position:'absolute',left:54,bottom:34,padding:'9px 13px',fontFamily:FONTS.mono,fontSize:16,color:dark?COLORS.ink500:COLORS.onInkMuted,background:dark?'rgba(245,240,230,.92)':'rgba(20,38,62,.82)',border:`1px solid ${dark?COLORS.rule:COLORS.borderOnInk}`}}>{children}</div>;

const SameGuest=()=>{const f=useCurrentFrame();const split=interpolate(f,[35,75],[0,1],{...clamp,easing:ease});const hit=spring({frame:f-16,fps:FPS,config:{damping:15,stiffness:150}});return <AbsoluteFill style={{background:COLORS.ink,overflow:'hidden'}}>
  <OffthreadVideo muted src={media('A001.mp4')} style={{width:'100%',height:'100%',objectFit:'cover',transform:'scale(1.05)'}}/>
  <AbsoluteFill style={{background:'linear-gradient(90deg,rgba(10,18,29,.08),rgba(10,18,29,.52))'}}/>
  <div style={{position:'absolute',inset:0,left:'51%',width:'49%',overflow:'hidden',borderLeft:`${8*split}px solid ${COLORS.goldBright}`,opacity:split}}><OffthreadVideo muted src={media('A001.mp4')} style={{width:1920,height:1080,objectFit:'cover',transform:'translateX(-960px) scaleX(-1) scale(1.05)'}}/></div>
  <div style={{position:'absolute',left:72,top:62,fontFamily:FONTS.mono,color:COLORS.goldBright,fontSize:19,letterSpacing:3}}>THE RETURNING-GUEST PROBLEM</div>
  <div style={{position:'absolute',left:68,bottom:76,opacity:hit,transform:`translateY(${(1-hit)*55}px)`,fontFamily:FONTS.display,fontWeight:850,fontSize:122,lineHeight:.83,letterSpacing:-6,color:COLORS.paper}}>SAME<br/><span style={{color:COLORS.goldBright}}>GUEST.</span></div>
  <div style={{position:'absolute',right:60,bottom:70,display:'flex',gap:10,opacity:split}}>{['FIRST BOOKING','RETURN BOOKING'].map((s,i)=><div key={s} style={{padding:'14px 18px',background:i?COLORS.negative:COLORS.draftingBlue,color:'white',fontFamily:FONTS.mono,fontSize:15,border:'1px solid rgba(255,255,255,.3)'}}>{s}<br/><b>COMMISSION</b></div>)}</div>
</AbsoluteFill>};

const Cloudbeds=()=>{const f=useCurrentFrame();const enter=spring({frame:f,fps:FPS,config:{damping:18,stiffness:100}});const zoom=interpolate(f,[35,250],[1,1.55],{...clamp,easing:ease});const hi=interpolate(f,[125,165],[0,1],clamp);return <AbsoluteFill style={{background:COLORS.paper,overflow:'hidden'}}>
  <div style={{position:'absolute',inset:52,overflow:'hidden',background:'white',border:`1px solid ${COLORS.ruleStrong}`,boxShadow:'0 22px 70px rgba(20,38,62,.18)',transform:`translateY(${(1-enter)*70}px) scale(${zoom})`,transformOrigin:'37% 60%'}}><Img src={media('A002.png')} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>
  <div style={{position:'absolute',right:70,top:84,width:520,padding:32,background:COLORS.navy,color:COLORS.paper,borderTop:`8px solid ${COLORS.goldBright}`,transform:`translateX(${(1-hi)*620}px)`}}><div style={{fontFamily:FONTS.mono,color:COLORS.goldBright,fontSize:17}}>CLOUDBEDS · COMPANY RESEARCH</div><div style={{fontFamily:FONTS.display,fontSize:81,fontWeight:850,lineHeight:.9,marginTop:17}}>MORE THAN<br/><span style={{color:COLORS.goldBright}}>60%</span></div><div style={{fontSize:23,lineHeight:1.25,marginTop:18}}>of independent-hotel reservations arrive through OTAs</div></div>
  <Source dark>Cloudbeds · 2026 lodging research · vendor-published</Source>
</AbsoluteFill>};

const Stay=()=>{const f=useCurrentFrame();const beat=Math.min(2,Math.floor(f/42));return <AbsoluteFill style={{background:COLORS.ink,overflow:'hidden'}}><OffthreadVideo muted src={media('A001.mp4')} startFrom={beat*24} style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:['30% 50%','65% 45%','48% 55%'][beat],transform:`scale(${1.03+(f%42)/1500})`}}/><AbsoluteFill style={{background:'linear-gradient(0deg,rgba(20,38,62,.72),transparent 55%)'}}/><div style={{position:'absolute',left:76,bottom:62,fontFamily:FONTS.display,fontWeight:850,fontSize:82,color:COLORS.paper}}>{['ARRIVES','STAYS','LEAVES HAPPY'][beat]}</div><div style={{position:'absolute',left:80,top:60,width:`${24+f/4}%`,height:7,background:COLORS.goldBright}}/></AbsoluteFill>};

const Booking=()=>{const f=useCurrentFrame();const pull=interpolate(f,[75,205],[0,1],{...clamp,easing:ease});const path=interpolate(f,[205,260],[0,1],{...clamp,easing:ease});return <AbsoluteFill style={{background:COLORS.paper,...grid}}>
  <div style={{position:'absolute',left:78,top:65,width:1400,height:870,overflow:'hidden',background:'white',border:'2px solid #B9B4A8',boxShadow:'18px 22px 0 rgba(20,38,62,.13)'}}><div style={{height:50,background:'#EEEAE0',display:'flex',alignItems:'center',gap:9,padding:'0 17px'}}>{[0,1,2].map(i=><i key={i} style={{width:12,height:12,borderRadius:99,background:['#9B3E2E','#C4A45F','#7B9E87'][i]}}/>)}<div style={{height:27,flex:1,marginLeft:10,background:'white',border:'1px solid #D2CCBE',paddingLeft:13,fontFamily:FONTS.mono,fontSize:12,lineHeight:'27px'}}>booking.com/searchresults</div></div><Img src={media('A011-booking-results.png')} style={{width:'100%',height:'calc(100% - 50px)',objectFit:'cover',objectPosition:'top'}}/></div>
  <div style={{position:'absolute',right:92+pull*175,top:350,width:220,height:220,borderRadius:'50%',background:COLORS.draftingBlue,border:'9px solid white',boxShadow:'0 20px 60px rgba(20,38,62,.3)',display:'grid',placeItems:'center',color:'white',fontFamily:FONTS.display,fontWeight:850,fontSize:31,textAlign:'center'}}>RETURNING<br/>GUEST</div>
  <svg style={{position:'absolute',inset:0,width:'100%',height:'100%'}}><path d="M1780 700 C1430 700 1360 750 1040 750 C760 750 690 655 390 655" fill="none" stroke={COLORS.goldBright} strokeWidth="18" pathLength="1" strokeDasharray="1" strokeDashoffset={1-path}/><path d="M390 655 L445 618 M390 655 L445 692" fill="none" stroke={COLORS.goldBright} strokeWidth="18" opacity={path}/></svg>
  <div style={{position:'absolute',right:74,bottom:46,fontFamily:FONTS.mono,fontSize:17,color:COLORS.goldOnPaper}}>BREAK THE RETURN PATH OUT.</div>
</AbsoluteFill>};

const Ident=()=>{const f=useCurrentFrame();const draw=interpolate(f,[0,55],[0,1],{...clamp,easing:ease});const hit=spring({frame:f-23,fps:FPS,config:{damping:16,stiffness:100}});return <AbsoluteFill style={{background:COLORS.navy,color:COLORS.paper,display:'grid',placeItems:'center',...grid}}><svg style={{position:'absolute',inset:0,width:'100%',height:'100%'}}><path d="M0 715 C330 715 410 370 810 370 C1130 370 1210 550 1920 550" fill="none" stroke={COLORS.goldBright} strokeWidth="14" pathLength="1" strokeDasharray="1" strokeDashoffset={1-draw}/></svg><div style={{position:'relative',padding:'42px 62px',background:COLORS.navy,border:`1px solid ${COLORS.borderOnInk}`,opacity:hit,transform:`scale(${.88+.12*hit})`}}><div style={{fontFamily:FONTS.display,fontSize:104,fontWeight:850,letterSpacing:-5,lineHeight:.85}}>THE OPERATOR<br/><span style={{color:COLORS.goldBright}}>ECONOMY</span></div><div style={{fontFamily:FONTS.mono,fontSize:21,letterSpacing:5,marginTop:30,color:COLORS.onInkMuted}}>BUILD · OWN · OPERATE</div></div></AbsoluteFill>};

const Thesis=()=>{const f=useCurrentFrame();const active=Math.min(2,Math.floor(f/75));return <AbsoluteFill style={{background:COLORS.paper,padding:'80px 100px',...grid}}><div style={{fontFamily:FONTS.mono,fontSize:17,letterSpacing:3,color:COLORS.goldOnPaper}}>ONE-PERSON BUSINESS SYSTEMS</div><div style={{display:'flex',gap:16,marginTop:25}}>{['BUILD','OWN','OPERATE'].map((w,i)=><div key={w} style={{flex:1,padding:'23px',background:i<=active?COLORS.navy:COLORS.paperSunken,color:i<=active?COLORS.paper:COLORS.ink500,fontFamily:FONTS.display,fontWeight:850,fontSize:53,borderTop:`7px solid ${i<=active?COLORS.goldBright:COLORS.ruleStrong}`}}>{w}</div>)}</div><div style={{fontFamily:FONTS.display,fontSize:92,fontWeight:850,letterSpacing:-4,lineHeight:.9,marginTop:90}}>DIRECT-BOOKING<br/><span style={{color:COLORS.goldOnPaper}}>RECOVERY.</span></div><div style={{position:'absolute',right:100,bottom:68,maxWidth:650,textAlign:'right',fontSize:26,color:COLORS.ink500}}>AI and practical workflows for the relationship after the stay.</div></AbsoluteFill>};

const Routes=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,270],[0,1],clamp);return <AbsoluteFill style={{background:COLORS.navy,color:COLORS.paper,padding:'78px 84px',...grid}}><div style={{fontFamily:FONTS.display,fontSize:72,fontWeight:850,lineHeight:.92}}>THE FIRST BOOKING<br/><span style={{color:COLORS.goldBright}}>ISN'T THE WHOLE RELATIONSHIP.</span></div><svg style={{position:'absolute',left:90,top:350,width:1740,height:500}} viewBox="0 0 1740 500"><path d="M40 110 H1650" stroke="#3E6FAE" strokeWidth="18" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/><path d="M1650 110 C1300 110 1310 360 880 360 H40" stroke={COLORS.goldBright} strokeWidth="18" fill="none" pathLength="1" strokeDasharray="1" strokeDashoffset={1-Math.max(0,(p-.35)/.65)}/>{[40,610,1120,1650].map((x,i)=><circle key={x} cx={x} cy="110" r="22" fill={i===3?COLORS.goldBright:'#3E6FAE'}/>)}</svg><div style={{position:'absolute',left:110,top:440,fontFamily:FONTS.mono,fontSize:19,color:'#8FB4E3'}}>DISCOVERY → OTA → FIRST BOOKING</div><div style={{position:'absolute',left:110,bottom:140,fontFamily:FONTS.mono,fontSize:19,color:COLORS.goldBright}}>STAY → RELATIONSHIP → DIRECT RETURN</div></AbsoluteFill>};

const Return=()=>{const f=useCurrentFrame();const hit=spring({frame:f,fps:FPS,config:{damping:18,stiffness:80}});return <AbsoluteFill style={{background:COLORS.paper,overflow:'hidden'}}><div style={{position:'absolute',left:65,top:65,width:1180,height:890,overflow:'hidden',clipPath:'polygon(0 0,100% 0,91% 100%,0 100%)'}}><OffthreadVideo muted src={media('A001.mp4')} startFrom={20} style={{width:'100%',height:'100%',objectFit:'cover',transform:'scale(1.08)'}}/></div><div style={{position:'absolute',right:74,top:145,width:585,opacity:hit,transform:`translateX(${(1-hit)*100}px)`}}><div style={{fontFamily:FONTS.mono,fontSize:17,color:COLORS.goldOnPaper}}>THE OUTCOME</div><div style={{fontFamily:FONTS.display,fontSize:72,fontWeight:850,lineHeight:.92,marginTop:18}}>WELCOME THEM<br/><span style={{color:COLORS.goldOnPaper}}>BACK DIRECTLY.</span></div><div style={{fontSize:26,lineHeight:1.3,color:COLORS.ink500,marginTop:30}}>The platform can own the introduction. The property should own what happens after the stay.</div></div><div style={{position:'absolute',left:65,bottom:50,width:`${hit*1780}px`,height:11,background:COLORS.goldFill}}/></AbsoluteFill>};

const Journey=()=>{const f=useCurrentFrame();const stages=['FIND','BOOK','WELCOME','REMEMBER','RETURN'];const active=Math.min(4,Math.floor(f/125));const p=interpolate(f,[0,660],[0,1],clamp);return <AbsoluteFill style={{background:COLORS.navy,color:COLORS.paper,padding:'66px 76px',overflow:'hidden',...grid}}><div style={{fontFamily:FONTS.mono,color:COLORS.goldBright,fontSize:17,letterSpacing:3}}>ONE GUEST · FIVE HANDOFFS · NO OWNER</div><div style={{fontFamily:FONTS.display,fontSize:68,fontWeight:850,marginTop:18}}>THE GUEST JOURNEY</div><div style={{position:'absolute',left:80,right:80,top:425,height:4,background:'rgba(245,240,230,.18)'}}/><div style={{position:'absolute',left:80,top:419,width:`${p*1760}px`,height:16,background:COLORS.goldBright}}/><div style={{position:'absolute',left:62,right:62,top:320,display:'flex',justifyContent:'space-between'}}>{stages.map((stage,i)=>{const on=i<=active;return <div key={stage} style={{width:305,height:280,padding:22,display:'flex',flexDirection:'column',justifyContent:'space-between',background:on?(i===4?COLORS.goldFill:COLORS.draftingBlue):COLORS.schemNodeBg,border:`2px solid ${on?COLORS.goldBright:COLORS.schemNodeBorder}`,opacity:on?1:.32,transform:`translateY(${on?0:35}px)`}}><div style={{fontFamily:FONTS.mono,fontSize:15}}>0{i+1}</div>{stage==='WELCOME'&&on?<div style={{height:105,overflow:'hidden',margin:'0 -8px'}}><OffthreadVideo muted src={media('A001.mp4')} startFrom={50} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>:<div style={{height:105,display:'grid',placeItems:'center',fontSize:48}}>{['⌕','▣','◇','≡','↩'][i]}</div>}<div style={{fontFamily:FONTS.display,fontWeight:850,fontSize:30}}>{stage}</div></div>})}</div><div style={{position:'absolute',left:80,bottom:58,fontSize:24,color:COLORS.onInkMuted}}>Discovery works. Booking works. The relationship breaks between systems.</div></AbsoluteFill>};

export const OEOpeningPilot:React.FC=()=><AbsoluteFill style={{background:COLORS.navy,fontFamily:FONTS.sans}}>
  <Audio src={staticFile('vo/hook.mp3')}/><Sequence from={s(28.13)} durationInFrames={s(61.87)}><Audio src={staticFile('vo/thesis.mp3')}/></Sequence>
  <Sequence durationInFrames={s(5.3)}><SameGuest/></Sequence><Sequence from={s(5.3)} durationInFrames={s(9.3)}><Cloudbeds/></Sequence><Sequence from={s(14.6)} durationInFrames={s(4.2)}><Stay/></Sequence><Sequence from={s(18.8)} durationInFrames={s(9.33)}><Booking/></Sequence>
  <Sequence from={s(28.13)} durationInFrames={s(8.57)}><Ident/></Sequence><Sequence from={s(36.7)} durationInFrames={s(8.6)}><Thesis/></Sequence><Sequence from={s(45.3)} durationInFrames={s(9.9)}><Routes/></Sequence><Sequence from={s(55.2)} durationInFrames={s(12.602)}><Return/></Sequence><Sequence from={s(67.802)} durationInFrames={s(22.198)}><Journey/></Sequence>
</AbsoluteFill>;
