"""Fail-closed audio inspection and the single permitted working conversion."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from .core import ValidationError, read_json, sha256_file


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(command, text=True, capture_output=True, check=False)
    except OSError as exc:
        raise ValidationError(f"cannot run {command[0]}: {exc}") from exc


def inspect_audio(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise ValidationError(f"audio file does not exist: {path}")
    result = _run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_streams",
            "-show_format",
            "-of",
            "json",
            str(path),
        ]
    )
    if result.returncode != 0:
        raise ValidationError(f"ffprobe rejected {path}: {result.stderr.strip()}")
    try:
        probe = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"ffprobe returned invalid JSON for {path}") from exc
    streams = [stream for stream in probe.get("streams", []) if stream.get("codec_type") == "audio"]
    if len(streams) != 1:
        raise ValidationError(f"expected exactly one audio stream, got {len(streams)}")
    stream = streams[0]
    codec = str(stream.get("codec_name", ""))
    try:
        sample_rate = int(stream.get("sample_rate"))
        channels = int(stream.get("channels"))
        duration = float(stream.get("duration") or probe.get("format", {}).get("duration"))
    except (TypeError, ValueError) as exc:
        raise ValidationError("ffprobe omitted required sample-rate, channel, or duration data") from exc
    bit_rate_raw = stream.get("bit_rate") or probe.get("format", {}).get("bit_rate")
    try:
        bit_rate = int(bit_rate_raw) if bit_rate_raw is not None else None
    except (TypeError, ValueError):
        bit_rate = None
    bits_raw = stream.get("bits_per_raw_sample") or stream.get("bits_per_sample")
    try:
        bit_depth = int(bits_raw) if bits_raw else None
    except (TypeError, ValueError):
        bit_depth = None
    codec_depths = {
        "pcm_s16le": 16,
        "pcm_s24le": 24,
        "pcm_s32le": 32,
        "pcm_f32le": 32,
        "pcm_f64le": 64,
    }
    bit_depth = bit_depth or codec_depths.get(codec)
    format_name = str(probe.get("format", {}).get("format_name", ""))
    if codec.startswith("pcm_"):
        origin_class = "native_pcm"
    elif codec == "mp3":
        origin_class = "lossy_mp3"
    else:
        origin_class = "unsupported"
    is_approved_mp3 = (
        codec == "mp3"
        and sample_rate == 44_100
        and channels == 1
        and bit_rate is not None
        and 190_000 <= bit_rate <= 194_000
    )
    is_working_master = (
        codec == "pcm_s24le"
        and sample_rate == 48_000
        and channels == 1
        and "wav" in format_name.split(",")
    )
    return {
        "path": str(path.resolve()),
        "sha256": sha256_file(path),
        "codec_name": codec,
        "container": format_name,
        "sample_rate_hz": sample_rate,
        "channels": channels,
        "bit_depth": bit_depth,
        "bit_rate_bps": bit_rate,
        "duration_seconds": duration,
        "origin_class": origin_class,
        "is_approved_mp3_fallback": is_approved_mp3,
        "is_working_master": is_working_master,
    }


def inspect_provider_raw_pcm(path: Path, receipt_path: Path, part_id: str | None = None) -> dict[str, Any]:
    """Inspect headerless provider PCM only when bound to a capture receipt.

    Raw S16LE has no self-describing header. Its byte geometry and immutable
    hash are checked here; codec/rate/channel claims must also match the
    credential-free provider receipt generated by this runtime.
    """
    if not path.is_file():
        raise ValidationError(f"raw PCM file does not exist: {path}")
    receipt = read_json(receipt_path)
    if receipt.get("schema_version") != "oe-provider-capture-run-v1":
        raise ValidationError("raw PCM requires an oe-provider-capture-run-v1 receipt")
    raw_hash = sha256_file(path)
    matches = [
        item
        for item in receipt.get("results", [])
        if isinstance(item, dict)
        and item.get("raw_sha256") == raw_hash
        and (part_id is None or item.get("part_id") == part_id)
    ]
    if len(matches) != 1:
        raise ValidationError("raw PCM hash/part does not match exactly one provider receipt result")
    item = matches[0]
    expected = {
        "requested_output_format": "pcm_48000",
        "actual_codec": "pcm_s16le",
        "container": "raw",
        "sample_rate_hz": 48_000,
        "channels": 1,
        "bit_depth": 16,
        "lossy_origin": False,
    }
    errors = [f"raw PCM receipt {key} mismatch" for key, value in expected.items() if item.get(key) != value]
    size = path.stat().st_size
    if size == 0 or size % 2:
        errors.append("raw PCM byte length is empty or not aligned to signed 16-bit samples")
    if errors:
        raise ValidationError(errors)
    return {
        "path": str(path.resolve()),
        "sha256": raw_hash,
        "codec_name": "pcm_s16le",
        "container": "raw",
        "sample_rate_hz": 48_000,
        "channels": 1,
        "bit_depth": 16,
        "bit_rate_bps": 768_000,
        "duration_seconds": size / (48_000 * 2),
        "origin_class": "native_pcm",
        "is_approved_mp3_fallback": False,
        "is_working_master": False,
        "capture_receipt_sha256": sha256_file(receipt_path),
        "part_id": item.get("part_id"),
    }


def validate_pcm_failure_receipt(receipt_path: Path, raw_path: Path) -> dict[str, Any]:
    receipt = read_json(receipt_path)
    errors: list[str] = []
    if receipt.get("schema_version") != "oe-pcm-capability-failure-v1":
        errors.append("fallback receipt must use oe-pcm-capability-failure-v1")
    if receipt.get("provider") != "elevenlabs":
        errors.append("fallback receipt provider must be elevenlabs")
    if receipt.get("attempted_output_format") != "pcm_48000":
        errors.append("fallback receipt must document a pcm_48000 attempt")
    if receipt.get("fallback_output_format") != "mp3_44100_192":
        errors.append("fallback receipt must authorize only mp3_44100_192")
    failure = receipt.get("failure")
    if not isinstance(failure, dict):
        errors.append("fallback receipt.failure must be an object")
        failure = {}
    status = failure.get("http_status")
    if status not in {400, 404, 422}:
        errors.append("fallback requires an explicit non-retryable 400, 404, or 422 PCM capability response")
    if failure.get("kind") != "pcm_capability_unavailable":
        errors.append("fallback failure.kind must be pcm_capability_unavailable")
    if failure.get("retryable") is not False:
        errors.append("fallback failure must explicitly be non-retryable")
    for field in ("provider_code", "message", "occurred_at"):
        if not isinstance(failure.get(field), str) or not failure.get(field):
            errors.append(f"fallback receipt.failure.{field} is required")
    raw = receipt.get("raw_output")
    if not isinstance(raw, dict):
        errors.append("fallback receipt.raw_output must be an object")
        raw = {}
    if raw.get("sha256") != sha256_file(raw_path):
        errors.append("fallback receipt raw-output hash does not match the immutable MP3")
    if errors:
        raise ValidationError(errors)
    return receipt


def convert_working(
    raw_path: Path,
    output_path: Path,
    receipt_path: Path | None = None,
    part_id: str | None = None,
) -> dict[str, Any]:
    if output_path.exists():
        raise ValidationError(f"refusing to overwrite working audio: {output_path}")
    before_hash = sha256_file(raw_path)
    raw_pcm = False
    try:
        source = inspect_audio(raw_path)
    except ValidationError as probe_error:
        if receipt_path is None:
            raise probe_error
        receipt = read_json(receipt_path)
        if receipt.get("schema_version") != "oe-provider-capture-run-v1":
            raise probe_error
        source = inspect_provider_raw_pcm(raw_path, receipt_path, part_id)
        raw_pcm = True
    lossy_origin = source["origin_class"] == "lossy_mp3"
    fallback_receipt_hash: str | None = None
    if lossy_origin:
        if not source["is_approved_mp3_fallback"]:
            raise ValidationError("lossy input must be mono MP3 at exactly 44.1 kHz and 192 kbps")
        if receipt_path is None:
            raise ValidationError("MP3 fallback requires an actual PCM-capability-failure receipt")
        validate_pcm_failure_receipt(receipt_path, raw_path)
        fallback_receipt_hash = sha256_file(receipt_path)
    elif source["origin_class"] != "native_pcm":
        raise ValidationError(f"unsupported source codec: {source['codec_name']}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "ffmpeg",
        "-nostdin",
        "-v",
        "error",
    ]
    if raw_pcm:
        command.extend(["-f", "s16le", "-ar", "48000", "-ac", "1"])
    command.extend([
        "-i",
        str(raw_path),
        "-map_metadata",
        "-1",
        "-vn",
        "-ac",
        "1",
        "-ar",
        "48000",
        "-c:a",
        "pcm_s24le",
        str(output_path),
    ])
    result = _run(command)
    if result.returncode != 0:
        if output_path.exists():
            output_path.unlink()
        raise ValidationError(f"ffmpeg conversion failed: {result.stderr.strip()}")
    if sha256_file(raw_path) != before_hash:
        raise ValidationError("raw source changed during conversion")
    converted = inspect_audio(output_path)
    if not converted["is_working_master"]:
        raise ValidationError("converted output is not 48 kHz, 24-bit, mono PCM WAV")
    return {
        "schema_version": "oe-working-conversion-v1",
        "raw": source,
        "raw_immutable_sha256": before_hash,
        "fallback_receipt_sha256": fallback_receipt_hash,
        "lossy_origin": lossy_origin,
        "conversion_count_from_raw": 1,
        "working": converted,
    }
